hardware_wheelchair:
  loop_hz: 10 # hz
  joints:
    - base_link_left_wheel_link_joint
    - base_link_right_wheel_link_joint
  diff_drive_pid:
    P: 0.45
    I: 10.0
    D: 0.0
    spacing: 0.6
    radius: 0.165
    max_velocity: 500