hardware_ttbot:
  loop_hz: 10 # hz
  joints:
    - base_link_left_wheel_link_joint
    - base_link_right_wheel_link_joint
  diff_drive_pid:
    P: 0.25
    I: 20.0
    D: 0.5
    spacing: 0.26
    radius: 0.033
    max_velocity: 1200
